# Generated by Django 2.1.3 on 2018-11-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrequest',
            name='email',
            field=models.EmailField(default='LSchaefer@hollandamerica.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programrequest',
            name='status',
            field=models.CharField(choices=[('ns', 'Not started (do not touch)'), ('ip', 'In progress'), ('fn', 'Finished')], default='ns', max_length=100),
        ),
    ]
