# Generated by Django 2.1.3 on 2018-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181117_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programrequest',
            name='id',
            field=models.CharField(default=5881, max_length=4, primary_key=True, serialize=False),
        ),
    ]
